In [17]:
import csv as csv
import numpy as np

csv_file = csv.reader(open('train.csv', 'rb'))
header = csv_file.next()
data = []

for row in csv_file:
    data.append(row)
data = np.array(data)

print data[0:5]

[['1' '0' '3' 'Braund, Mr. Owen Harris' 'male' '22' '1' '0' 'A/5 21171'
  '7.25' '' 'S']
 ['2' '1' '1' 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
  'female' '38' '1' '0' 'PC 17599' '71.2833' 'C85' 'C']
 ['3' '1' '3' 'Heikkinen, Miss. Laina' 'female' '26' '0' '0'
  'STON/O2. 3101282' '7.925' '' 'S']
 ['4' '1' '1' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)' 'female' '35'
  '1' '0' '113803' '53.1' 'C123' 'S']
 ['5' '0' '3' 'Allen, Mr. William Henry' 'male' '35' '0' '0' '373450'
  '8.05' '' 'S']]


In [18]:
type(data[0:15,5])

numpy.ndarray

In [19]:
import pandas as pd
import numpy as np

# For .read_csv, always use header=0 when you know row 0 is the header row
df = pd.read_csv('train.csv', header=0)

df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [20]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [21]:
df[['Sex', 'Pclass', 'Age']]
df[df['Age'] > 60][['Sex', 'Pclass', 'Age', 'Survived']]
df[df['Age'].isnull()][['Sex', 'Pclass', 'Age']]
print ''

In [22]:
for i in range(1,4):
    print i, len(df[ (df['Sex'] == 'male') & (df['Pclass'] == i) ])

1 122
2 108
3 347


In [23]:
import matplotlib.pylab as P

df['Age'].dropna().hist(bins=16, range=(0,80), alpha = .5)
P.show()

In [25]:
# female has value 0 and male has value 1
df['Gender'] = df['Sex'].map( {'female': 0, 'male' : 1} ).astype(int)
# df.head(2)

In [26]:
median_ages = np.zeros((2,3))
median_ages

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [29]:
for i in range(0, 2):
    for j in range(0, 3):
        median_ages[i, j] = df[ (df['Gender'] == i) & (df['Pclass'] == j+1) ]['Age'].dropna().median()
        
median_ages

array([[ 35. ,  28. ,  21.5],
       [ 40. ,  30. ,  25. ]])

In [43]:
df['AgeFill'] = df['Age']
df[ df['Age'].isnull() ][['Gender','Pclass','Age','AgeFill']].head(10)

# for row in range(df[df['Age'].isnull()]):
#     print row
# for i in df[ df['Age'].isnull()]:
#     print i
for i in range(0,2):
    for j in range(0,3):
        df.loc[ (df['Age'].isnull()) & (df['Gender'] == i) & (df['Pclass'] == j+1), 'AgeFill'] = median_ages[i, j]
        
df[ df['Age'].isnull() ][['Gender','Pclass','Age','AgeFill']].head(10)

Gender  Pclass  Age  AgeFill
5        1       3  NaN     25.0
17       1       2  NaN     30.0
19       0       3  NaN     21.5
26       1       3  NaN     25.0
28       0       3  NaN     21.5
29       1       3  NaN     25.0
31       0       1  NaN     35.0
32       0       3  NaN     21.5
36       1       3  NaN     25.0
42       1       3  NaN     25.0

In [50]:
df['AgeIsNull'] = pd.isnull(df.Age).astype(int)
df.describe()
# np.sum(df['AgeIsNull']) / float(len(df['AgeIsNull']))

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare      Gender     AgeFill   AgeIsNull  
count  891.000000  891.000000  891.000000  891.000000  891.000000  
mean     0.381594   32.204208    0.647587   29.112424    0.198653  
std      0.806057   49.693429    0.477990   13.304424    0.399210  
min      0.000000    0.000000    0.000000    0.420000    0.000000  
25%      0.000000    7.910400    0.000000   21.500000    0.000000  
50%      0.000000   14.454200    1.000000   26.000000    0.000000  
75%      0.000000   31.000000    1.000000   36.000000    0.000000  
max      6.000000  512.329200    1.000000   80.000000    1.000000

In [54]:
df['FamilySize'] = df['Parch'] + df['SibSp']
df['Age*Class'] = df.AgeFill * df.Pclass

df['FamilySize'].hist()
P.show()
df['Age*Class'].hist()
P.show()

In [57]:
df.dtypes[df.dtypes.map(lambda x: x=='object')]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [61]:
df = df.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked', 'Age'], axis=1)

ValueError: labels ['Name' 'Sex' 'Ticket' 'Cabin' 'Embarked' 'Age'] not contained in axis

In [63]:
df.head()

PassengerId  Survived  Pclass  SibSp  Parch     Fare  Gender  AgeFill  \
0            1         0       3      1      0   7.2500       1       22   
1            2         1       1      1      0  71.2833       0       38   
2            3         1       3      0      0   7.9250       0       26   
3            4         1       1      1      0  53.1000       0       35   
4            5         0       3      0      0   8.0500       1       35   

   AgeIsNull  FamilySize  Age*Class  
0          0           1         66  
1          0           1         38  
2          0           0         78  
3          0           1         35  
4          0           0        105

In [64]:
train_data = df.values
train_data

array([[   1. ,    0. ,    3. , ...,    0. ,    1. ,   66. ],
       [   2. ,    1. ,    1. , ...,    0. ,    1. ,   38. ],
       [   3. ,    1. ,    3. , ...,    0. ,    0. ,   78. ],
       ..., 
       [ 889. ,    0. ,    3. , ...,    1. ,    3. ,   64.5],
       [ 890. ,    1. ,    1. , ...,    0. ,    0. ,   26. ],
       [ 891. ,    0. ,    3. , ...,    0. ,    0. ,   96. ]])